### ISSUE TITLE
Support React exports of PropTypes, Children, ... etc

### ISSUE THREAD

**Issue by jhen0409** [sibeliusseraphini/codemod-RN24-to-RN25#1]
https://github.com/facebook/react/blob/master/src/isomorphic/React.js#L57-L88

We can also move them to React import, not just the `Component`?

**Comment by grabbou** [comment]
+1 for PropTypes, I've seen it in few places. Maybe an array of keys to check and mark as React API? (or even just download react as a dependency and check it)

**Comment by sibeliusseraphini** [comment]
I need a generic import check like this one for component, https://github.com/sibeliusseraphini/codemod-RN24-to-RN25/blob/master/transform.js#L10

This will not be hard, I will try to fix this tm, feel free to send a PR
