### ISSUE TITLE
unable to get single quotes using the provided example

### ISSUE THREAD

**Issue by ultralame** [sibeliusseraphini/codemod-RN24-to-RN25#5]
i'm doing `jscodeshift -t transform.js ../Project/src/ --printOptions='{"quote":"single"}'` and i'm getting double quotes. any idea what i might be doing wrong?

thanks!

**Comment by sibeliusseraphini** [comment]
You can modify the `transform.js` to add this options like in the jscodeshif readme - https://github.com/facebook/jscodeshift#passing-options-to-recast

but it should work fine as is the same usage of react-codemod https://github.com/reactjs/react-codemod#recast-options

you can check the recast options here: https://github.com/benjamn/recast/blob/52a7ec3eaaa37e78436841ed8afc948033a86252/lib/options.js#L61

**Comment by sibeliusseraphini** [comment]
so, I need to read the printOptions on my transform

like this: https://github.com/reactjs/react-codemod/blob/master/transforms/pure-component.js#L19

could you submit a PR to fix this?

**Comment by ultralame** [comment]
thanks for the quick response! one small follow up question: do you happen to know any good options for adding whitespace around  curly braces?

i prefer to do object literals and destructuring `{ foo }` 
and JSX/string interpolation `{foo}`

couldn't find any recast options for that and i'm hoping to find a way out of doing it manually

**Comment by sibeliusseraphini** [comment]
cc @cpojer
