### ISSUE TITLE
Add support for separate import and destructuring

### ISSUE THREAD

**Issue by ultralame** [sibeliusseraphini/codemod-RN24-to-RN25#7]
example:
```js
import React from 'react-native';
const {
  Component,
  View,
  Text,
} = React;
```

turns out almost half of the components in my project are written this way 😿 

i imagine i'm not the only person with this problem so if i get it working i'll send a PR. this is my first time working with code transformations so it might take me a while to figure this out

**Comment by sibeliusseraphini** [comment]
I think it is related to recast.

Codemods are fun to write!

**Comment by reergymerej** [comment]
This is not quite fixed yet, but a test has been added for it. #9 I think. I'll try and solve it tonight.
